apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: <docker-username>/frontend-app:latest
        ports:
        - containerPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: <docker-username>/backend-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: DB_NAME
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: DB_PORT
        - name: ALLOWED_ORIGINS
          valueFrom:
            secretKeyRef:
              name: ALLOWED_ORIGINS
