name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t frontend-app:latest -f frontend/Dockerfile .
          docker tag frontend-app:latest ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest

      - name: Build and Push Backend Docker Image
        run: |
          docker build -t backend-app:latest -f backend/Dockerfile .
          docker tag backend-app:latest ${{ secrets.DOCKER_USERNAME }}/backend-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-app:latest

      - name: Deploy to Kubernetes
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          ALLOWED_ORIGINS: ${{ secrets.ALLOWED_ORIGINS }}
        run: |
          ssh -o StrictHostKeyChecking=no -i <your-key-pair>.pem ubuntu@<instance_ip> "
          kubectl apply -f /path/to/k8s/deployment.yaml &&
          kubectl apply -f /path/to/k8s/service.yaml
          "
